=== gitpan/XML-XSH/src/recdescent.dtd
<?xml version='1.0' encoding='utf-8'?>

<!-- ============================================================= -->
<!--                    RecDescent grammar definition DTD          -->
<!-- ============================================================= -->

<!--                    Paragraph Content                          -->
<!--                    Content allowed inside paragraphs          -->
<!ENTITY % paracont    "#PCDATA | xref | link | typeref"             >


<!--                    RecDescent                                 -->
<!--                    RecDescent grammar and documentation
                        definition                                 -->
<!ELEMENT  recdescent-xml (description?, preamb?, postamb?, rules+)  >

<!--                    Preambule                                  -->
<!--                    Code to be inserted before the grammar.    -->
<!ELEMENT  preamb       (#PCDATA)                                    >

<!--                    Postambule                                 -->
<!--                    Code to be inserted after the grammar.     -->
<!ELEMENT  postamb      (#PCDATA)                                    >


<!--                    Rules                                      -->
<!ELEMENT  rules        (rule)*                                      >



<!--                    Rule                                       -->
<!--                    RecDescent grammar rule, its action and,
                        optionally, documentation                  -->
<!ELEMENT  rule        (aliases?, production+, comment?, documentation?) >
<!--         id         rule identificator
             type       rule type (you may categorize your rules
             name       rule/command descriptive name             
             regexp     (optional) formal way to match the command
                        name                                       -->
<!ATTLIST  rule                                                      
             id         ID                                 #REQUIRED
             type       CDATA                              #IMPLIED
             name       CDATA                              #IMPLIED
             regexp     CDATA                              #IMPLIED  >


<!--                    Aliases                                    -->
<!--                    Command name aliases                       -->
<!ELEMENT  aliases      (alias+)                                     >
<!--                    Alias                                      -->
<!--                    Command name alias                         -->
<!ELEMENT  alias        EMPTY                                        >
<!--         regexp     (optional) formal way to match the command
                         name                                      -->
<!ATTLIST  alias
             name       CDATA                              #REQUIRED
             regexp     CDATA                              #IMPLIED  >


<!--                    Production                                 -->
<!--                    The rule production                        -->
<!ELEMENT  production   (selfref | group | regexp | directive | ruleref | literal | action)*    >



<!--                    RegExp                                     -->
<!--                    Token matched by a regular expression      -->
<!ELEMENT  regexp       (#PCDATA)                                    >



<!--                    RecDescent directive                       -->
<!ELEMENT  directive    (#PCDATA)                                    >
<!--         type       Directive type                             -->
<!ATTLIST  directive
             type
                        (commit|uncommit|reject|score|autoscore|skip|resync|error|rulevar|matchrule|leftop|rightop|defer|nocheck|perl_quotelike|perl_codeblock|perl_variable|token)


                                                           #REQUIRED >
<!--                    Sub-Rule                                   -->
<!--                    Ruleref reference                          -->
<!ELEMENT  ruleref      EMPTY                                        >
<!--         rep        repetition suffix                          -->
<!ATTLIST  ruleref
             ref        IDREF                              #REQUIRED
             rep        CDATA                              #IMPLIED  >

<!--                    Literal                                    -->
<!--                    Literal value                              -->
<!ELEMENT  literal      (#PCDATA)                                    >




<!--                    Action                                     -->
<!--                    Perl code which is evaluated on successful
                        production                                 -->
<!ELEMENT  action       (#PCDATA)                                    >



<!--                    Documentation                              -->
<!--                    Rule documentation                         -->
<!ELEMENT  documentation (title?, usage?, description?, see-also?)   >



<!--                    Usage                                      -->
<!--                    Usage description                          -->
<!ELEMENT  usage        (%paracont;)*                                >



<!--                    Description                                -->
<!--                    Command description                        -->
<!ELEMENT  description  (para | code | example)*                     >


<!--                    See-also                                   -->
<!--                    List of related rules/commands             -->
<!ELEMENT  see-also     (ruleref+)                                   >



<!--                    Comment                                    -->
<!--                    A comment                                  -->
<!ELEMENT  comment      (#PCDATA)                                    >


<!--                    Xref                                       -->
<!--                    Automatic cross-reference                  -->
<!ELEMENT  xref         EMPTY                                        >
<!ATTLIST  xref
             linkend    IDREF                              #REQUIRED >

<!--                    TypeRef                                    -->
<!--                    Reference to all rules of a given type     -->
<!ELEMENT  typeref      EMPTY                                        >
<!--         types      space separated list of target types       -->
<!ATTLIST  typeref
             types      CDATA                              #REQUIRED >


<!--                    Link                                       -->
<!--                    Textual cross-reference                    -->
<!ELEMENT  link         (#PCDATA)                                    >
<!ATTLIST  link
             linkend    IDREF                              #REQUIRED >


<!--                    Paragraph                                  -->
<!ELEMENT  para         (%paracont;)*                                >

<!--                    Title                                      -->
<!--                    Rule documentation/example title           -->
<!ELEMENT  title        (#PCDATA)                                    >


<!--                    Group                                      -->
<!--                    Group of alternative productions           -->
<!ELEMENT  group        (production+)                                >


<!--                    SelfRef                                    -->
<!--                    Inserts a production item which is matched
                        by command name or any alias               -->
<!ELEMENT  selfref      EMPTY                                        >


<!--                    Example                                    -->
<!--                    Example in command or rule description     -->
<!ELEMENT  example      (title?,code+)                               >

<!--                    Code                                       -->
<!--                    A block of formatted programming code      -->
<!ELEMENT  code         (#PCDATA)                                    >


<!-- ============================================================= -->
<!--                    End of RecDescent command definition DTD   -->
<!-- ============================================================= -->

=== gitpan/XML-XSH/src/xsh_grammar.xml
<?xml version="1.0"?>
<!DOCTYPE recdescent-xml SYSTEM "recdescent.dtd">
<recdescent-xml>
  <doc>
    <title>XSH</title>
    <shortdesc>XML Editing Shell</shortdesc>
    <description>
      <para>
	XSH acts as a command interpreter.  Individual commands must
	be separated with a semicolon. Each command may be followed by
	a pipeline redirection to capture the command's output. In the
	interactive shell, backslash may be used at the end of line to
	indicate that the command follows on the next line.
      </para>
      <para>
	A pipeline redirections may be used either to feed the
	command's output to a unix command or to store it in a XSH
	string variable.</para> <para>In the first case, the syntax is
	<literal>xsh-command | shell-command ;</literal> where
	<literal>xsh-command</literal> is any XSH
	command and <literal>shell-command</literal> is any command (or code) recognized
	by the default shell interpreter of the operating system
	(i.e. on UNIX systems by <literal>sh</literal> or
	<literal>csh</literal>, on Windows systems by
	<literal>cmd</literal>).  Brackets may be used to join more shell commands (may
	depend on which shell is used).
      </para>
      <example>
	<title>Count attributes of words containing string foo in its name or value.</title>
	<code>xsh&gt; <userinput>ls //words/@* | grep foo | wc</userinput></code>
      </example>
      <para>
	In order to store a command's output in a string variable, the
	pipeline redirection must take the form <literal>xsh-command
	|&gt; $variable</literal> where <literal>xsh-command</literal> is
	any XSH command and <literal>$variable</literal> is any valid
	name for a string <link linkend="Variables">variable</link>.
      </para>
      <example>
	<title>Store the number of all words in a variable named count.</title>
	<code>xsh&gt; <userinput>count //words |&gt; $count</userinput></code>
      </example>
      <para>
	<literal><xref linkend="help_command"/> command</literal>
	gives a list of all XSH commands.
      </para>
      <para>
	<literal><xref linkend="help_command"/> type</literal> gives a
	list of all argument types.
      </para>
      <para>
	<literal><xref linkend="help_command"/></literal> followed by
	a command or type name gives more information on the
	particular command or argument type.
      </para>
    </description>
    <section id="Documents">
      <title>Files/Documents</title>
      <para>
	XSH is intended to query and manipulate XML and HTML
	documents. Use one of the
	<literal>open/open-*/create</literal> commands to load an XML
	or HTML document from a local file, external URL (such as
	http:// or ftp://), string or pipe.  While loading, XSH parses
	and optionally validates (see <xref linkend="validation"/> and
	<xref linkend="load_ext_dtd"/>) the document. Parsed documents
	are stored in memory as <ulink url="http://www.w3.org/DOM/">DOM</ulink> trees, that can be
	<link linkend="Navigation">navigated</link> and <link linkend="Manipulation">manipulated</link> quite similarly to a
	local filesystem.
      </para>
      <para>
	Every opened document is associated with an identifier (<xref linkend="ID"/>), that is a symbolic name for the document in
	  XSH and can be used for example as a prefix of <xref linkend="xpath"/>.
      </para>
      <para>
	In the current version, XSH is only able to save documents
	locally.  To store a document on any other location, use <xref linkend="list_command"/> command and pipe redirection to feed
	the XML representation of the document to any external program
	that is able to store it on a remote location.
      </para>
      <example>
	<title>Store XSH document DOC on a remote machine using Secure Shell</title>
	<code>xsh&gt; <userinput>ls DOC:/ | ssh my.remote.org 'cat &gt; test.xml'</userinput></code>
      </example>
    </section>
    <section id="Navigation">
      <title>Tree navigation</title>
      <para>
	With XSH, it is possible to browse <link
	linkend="Documents">document trees</link> as if they were a
	local filesystem, except that <link
	linkend="xpath">XPath</link> expressions are used instead of
	ordinary UNIX paths.</para> <para>Current position in the
	document tree is called the <emphasis>current node</emphasis>.
	Current node's XPath may be queried with <xref
	linkend="pwd_command"/> command.  In the interactive shell,
	current node is also displayed in the command line
	prompt. Remember, that beside <xref
	linkend="chxpath_command"/> command, current node (and
	document) is silently changed by all variant of <xref
	linkend="open_command"/> command, <xref
	linkend="create_command"/> command and temporarily also by the
	node-list variant of the <xref linkend="foreach"/>
	statement.
      </para>
      <para>Documents are specified
	in a similar way as harddrives on DOS/Windows(TM) systems
	(except that their names are not limitted to one letter in
	XSH), i.e. by a prefix of the form doc: where doc is the
	<xref linkend="ID"/> associated with the document.
      </para>
      <para>
	To mimic the filesystem navigation as closely as
	possible, XSH contains several commands named by analogy of
	UNIX filesystem commands, such as <xref linkend="chxpath_command"/>, <xref linkend="list_command"/> and
	<xref linkend="pwd_command"/>.	
      </para>
      <example>
	<code>xsh scratch:/&gt; <userinput>open docA=&quot;testA.xml&quot;</userinput>
	  xsh docB:/&gt; <userinput>open docB=&quot;testB.xml&quot;</userinput>
	  xsh&gt; <userinput>pwd</userinput>
	  docB:/
	  xsh docB:/&gt; <userinput>cd docA:/article/chapter[title='Conclusion']</userinput>
	  xsh docA:/article/chapter[5]&gt; <userinput>pwd</userinput>
	  docA:/article/chapter[5]
	  xsh docA:/article/chapter[5]&gt; <userinput>cd previous-sibling::chapter</userinput>
	  xsh docA:/article/chapter[4]&gt; <userinput>cd ..</userinput>
	  xsh docA:/article&gt; <userinput>select docB</userinput>
	  xsh docB:/&gt;
	</code>
      </example>
    </section>
    <section id="Manipulation">
      <title>Tree modification</title>
      <para>
	XSH provides mechanisms not only to browse and inspect the DOM
	tree but also to modify its content by providing commands for
	copying, moving, and deleting its nodes as well as adding
	completely new nodes or XML fragments to it. It is quite easy
	to learn these commands since their names or aliases mimic
	their well-known filesystem analogies.  On the other hand,
	many of these commands have two versions one of which is
	prefixed with a letter &quot;x&quot;. This &quot;x&quot;
	stands for &quot;cross&quot;, thus e.g. <xref
	linkend="xcopy_command"/> should be read as &quot;cross
	copy&quot;. Let's explain the difference on the
	example of <xref linkend="xcopy_command"/>.</para>
      <para>
	When you copy, you have to specify what are you copying and
	where are you copying to, so you have to specify the
	<emphasis>source</emphasis> and the
	<emphasis>target</emphasis>.  XSH is very much XPath-based so,
	XPath is used here to specify both of them. However, there
	might be more than one node that satisfies an XPath expression. So,
	the rule of thumb is that the &quot;cross&quot; variant of a
	command places <emphasis>one and every</emphasis> of the source nodes
	to the location of <emphasis>one and every</emphasis> destination
	node, while the plain variant works one-by-one, placing the
	first source node to the first destination, the second source
	node to the second destination, and so on (as long as there
	are both source nodes and destinations left).
      </para>
      <example>
	<code>xsh&gt; <userinput>create a &quot;&lt;X&gt;&lt;A/&gt;&lt;Y/&gt;&lt;A/&gt;&lt;/X&gt;&quot;;</userinput>
	  xsh&gt; <userinput>create b &quot;&lt;X&gt;&lt;B/&gt;&lt;C/&gt;&lt;B/&gt;&lt;C/&gt;&lt;B/&gt;&lt;/X&gt;&quot;;</userinput>
	  xsh&gt; <userinput>xcopy a://A replace b://B;</userinput>
	  xsh&gt; <userinput>copy b://C before a://A;</userinput>
	  xsh&gt; <userinput>ls a:/;</userinput>
	  &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
	  &lt;X&gt;&lt;C/&gt;&lt;A/&gt;&lt;Y/&gt;&lt;C/&gt;&lt;A/&gt;&lt;/X&gt;

	  xsh&gt; <userinput>ls b:/;</userinput>
	  &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
	  &lt;X&gt;&lt;A/&gt;&lt;A/&gt;&lt;C/&gt;&lt;A/&gt;&lt;A/&gt;&lt;C/&gt;&lt;A/&gt;&lt;A/&gt;&lt;/X&gt;
	</code>
      </example>
      <para>
	As already indicated by the example, another issue of tree
	modification is the way in which the destination node
	determines the target location. Should the source node be
	placed before, after, or into the resulting node? Should it
	replace it completely? This information has to be given in the
	<xref linkend="loc"/> argument that usually precedes the
	destination XPath.
      </para>
      <para>
	Now, what happens if source and destination nodes are of
	incompatible types? XSH tries to avoid this by implicitly
	converting between node types when necessary.  For example, if
	a text, comment, and attribute node is copied into, before or
	after an attribute node, the original value of the
	attribute is replaced, prepended or appended respectively with
	the textual content of the source node. Note however, that
	<emphasis>element nodes are never converted</emphasis> into
	text, attribute or any other textual node.  There
	are many combinations here, so try yourself and see the
	results.
      </para>
      <para>You may even use some more sofisticated way to convert
	between node types, as shown in the following example, where
	an element is first commented out and than again uncommented.
	Note, that the particular approach used for resurrecting the
	commented XML material works only for well-balanced chunks of
	XML.
      </para>
      <example>
	<title>Using string variables to convert between different
	  types of nodes</title>
	<code>
	  <userinput>create doc &lt;&lt;EOF;
	  &lt;?xml version='1.0'?&gt;
	    &lt;book&gt;
	    <tab/>&lt;chapter&gt;
	  <tab count="2"/>&lt;title&gt;Intro&lt;/title&gt;
	  <tab/>&lt;/chapter&gt;
